application: aeboilerplate
version: 1
runtime: python27
api_version: 1
threadsafe: yes


handlers:

- url: /favicon\.ico
  static_files: assets/img/favicon.ico
  upload: favicon\.ico
  expiration: 7d
  http_headers:
    Last-Modified: "Tue, 07 May 2013 00:00:00 GMT"

- url: /assets
  static_dir: assets
  expiration: 7d
  http_headers:
    Last-Modified: "Tue, 10 May 2013 00:00:00 GMT"

- url: .*
  script: main.app


libraries:

- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest
